apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insighthub.fullname" . }}-config
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.runtime.environment | quote }}
  RAG_MODE: {{ .Values.runtime.ragMode | quote }}
  LLM_PROVIDER: {{ .Values.runtime.llmProvider | quote }}
  EMBEDDING_PROVIDER: {{ .Values.runtime.embeddingProvider | quote }}
  EMBEDDING_DIM: {{ .Values.runtime.embeddingDimension | quote }}
  QUEUE_NAME: {{ .Values.runtime.queueName | quote }}
