{{- if .Values.platform.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insighthub.serviceAccountName" . }}
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
  {{- with .Values.platform.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
