apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insighthub.fullname" . }}-web
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate: {maxUnavailable: 0, maxSurge: 1}
  selector:
    matchLabels:
      {{- include "insighthub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "insighthub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "insighthub.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: web
          image: "{{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}"
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - {name: http, containerPort: 3000}
          env:
            - name: API_INTERNAL_URL
              value: http://{{ include "insighthub.fullname" . }}-api:8000
          startupProbe:
            httpGet: {path: /api/health, port: http}
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet: {path: /api/health, port: http}
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /api/health, port: http}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
            - {name: next-cache, mountPath: /app/.next/cache}
      volumes:
        - name: tmp
          emptyDir: {sizeLimit: 64Mi}
        - name: next-cache
          emptyDir: {sizeLimit: 128Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insighthub.fullname" . }}-web
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if eq .Values.ingress.className "alb" }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  {{- end }}
spec:
  selector:
    {{- include "insighthub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - {name: http, port: 3000, targetPort: http}
